'use client';
import { useState, useEffect, useCallback, useRef } from 'react';
import { Wallet, ChartNoAxesCombined, History, Cable, RefreshCw, Pencil, ShieldCheck, ChevronRight, Eye, ArrowUpRight } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from '@/components/ui/sidebar';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import type { Ledger, Asset, Period } from '@/lib/types';
import { ImportLedgerDialog } from './import-ledger-dialog';
import { AssetTrend } from './asset-trend';
import { WithdrawalsPanel } from './withdrawals-panel';
import { assetMeasures, embeddedWithdrawals, chinaDay, periodMeasures } from '@/lib/withdrawals';

const money=(n:number,d=2)=>n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const stamp=(s:string|null)=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'尚未同步';
const viewNames={overview:'资产总览',history:'历史记录',withdrawals:'出金记录',connections:'交易所连接'};
type View=keyof typeof viewNames;
async function api(path:string,method='GET',body?:unknown):Promise<Ledger>{
 const r=await fetch(path,{method,headers:method==='GET'?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});
 const data=await r.json() as Ledger & {error?:string};if(!r.ok)throw new Error(data.error||'请求失败，请稍后重试');return data;
}
function badge(a:Asset,now:number){
 if(a.mode!=='manual'&&a.status.includes('同步')&&!a.error&&now-new Date(a.updatedAt).getTime()>300000)return '数据已过期 · 保留旧值';
 if(a.mode==='market'&&!a.error&&now-new Date(a.updatedAt).getTime()>900000)return '行情已过期 · 保留旧值';
 return a.status;
}
export default function Dashboard({initial}:{initial:Ledger}){
 const [ledger,setLedger]=useState(initial),[filter,setFilter]=useState('all'),[view,setView]=useState<View>('overview');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now());
 const [editing,setEditing]=useState<Asset|null>(null),[quantity,setQuantity]=useState(''),[price,setPrice]=useState('');
 const [fxOpen,setFxOpen]=useState(false),[fx,setFx]=useState(String(initial.fx)),[formError,setFormError]=useState('');
 const [connectTo,setConnectTo]=useState<'bybit'|'aster'|null>(null),[key,setKey]=useState(''),[secret,setSecret]=useState(''),[includeSpot,setIncludeSpot]=useState(false),[region,setRegion]=useState('global');
 const [detail,setDetail]=useState<Asset|null>(null),[period,setPeriod]=useState<Period|null>(null),[periodRows,setPeriodRows]=useState<Asset[]>([]);
 const busyRef=useRef(false),importOpenRef=useRef(false);
 const [importOpen,setImportOpen]=useState(false);
 function toggleImport(open:boolean){importOpenRef.current=open;setImportOpen(open);}
 const refresh=useCallback(async(manual=false)=>{
  if(busyRef.current||importOpenRef.current)return;busyRef.current=true;setBusy(true);
  try{const data=await api('/api/sync','POST',{});setLedger(data);setError('');if(manual)toast.success('已完成刷新，更新状态见资产明细');}
  catch(e){setError(e instanceof Error?e.message:'更新失败');}
  finally{setBusy(false);busyRef.current=false;setNow(Date.now());}
 },[]);
 useEffect(()=>{
  const sync=()=>{if(document.visibilityState==='visible'&&navigator.onLine)void refresh();else setNow(Date.now());};
  sync();const timer=setInterval(sync,60000);document.addEventListener('visibilitychange',sync);window.addEventListener('online',sync);
  return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',sync);window.removeEventListener('online',sync);};
 },[refresh]);
 useEffect(()=>{
  const read=()=>{const v=location.hash.slice(1);if(v in viewNames)setView(v as View);};read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read);
 },[]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  Promise.resolve(context.registerTool({name:'read_asset_ledger',description:'读取当前资产估值、单价、来源及更新时间，不进行同步或修改。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('无需参数');return {assets:ledger.assets,fx:ledger.fx,baselineDate:ledger.baselineDate};}},{signal:lifecycle.signal})).catch(()=>{});
  return()=>lifecycle.abort();
 },[ledger]);
 function navigate(v:View){setView(v);location.hash=v;window.scrollTo({top:0});}
 async function mutate(path:string,method:string,body:unknown,onSuccess:()=>void){
  if(busyRef.current)return;busyRef.current=true;setBusy(true);setFormError('');
  try{setLedger(await api(path,method,body));setError('');onSuccess();toast.success('已保存');}
  catch(e){setFormError(e instanceof Error?e.message:'保存失败，输入已保留');}
  finally{busyRef.current=false;setBusy(false);}
 }
 function edit(a:Asset){setEditing(a);setQuantity(String(a.quantity??0));setPrice(a.price===null?'':String(a.price));setFormError('');}
 function connection(exchange:'bybit'|'aster'){setConnectTo(exchange);setKey('');setSecret('');setIncludeSpot(false);setFormError('');}
 async function openPeriod(p:Period){
  setPeriod(p);setPeriodRows([]);setFormError('');
  try{const r=await fetch('/api/history?id='+encodeURIComponent(p.id),{cache:'no-store'});const data=await r.json() as {error?:string;rows:Asset[]};if(!r.ok)throw new Error(data.error);setPeriodRows(data.rows);}
  catch(e){setFormError(e instanceof Error?e.message:'无法读取历史明细');}
 }
 const total=ledger.assets.reduce((s,a)=>s+(a.value??0),0);
 const rows=ledger.assets.filter(a=>filter==='all'||(filter==='manual'?a.mode==='manual':a.mode!=='manual')).sort((a,b)=>(b.value??0)-(a.value??0));
 const today=chinaDay(new Date(now));
 const measures=assetMeasures(total,embeddedWithdrawals(ledger.assets),ledger.withdrawals,today);
 const pending=Object.values(ledger.connections).filter(c=>!c.configured).length;
 const failures=ledger.assets.filter(a=>a.error);
 const nav=[{id:'overview' as View,label:'资产总览',Icon:ChartNoAxesCombined},{id:'history' as View,label:'历史记录',Icon:History},{id:'withdrawals' as View,label:'出金记录',Icon:ArrowUpRight},{id:'connections' as View,label:'交易所连接',Icon:Cable}];
 const renderTable=(assets:Asset[],editable=true)=><Table><TableHeader><TableRow><TableHead>项目 / 资产</TableHead><TableHead>类型</TableHead><TableHead className="numeric">数量</TableHead><TableHead className="numeric">单价 / USD</TableHead><TableHead className="numeric">估值 / USD</TableHead>{editable&&<><TableHead>数据来源 / 更新时间</TableHead><TableHead>操作</TableHead></>}</TableRow></TableHeader><TableBody>{assets.map(a=><TableRow key={a.id}><TableCell><strong className="asset-name">{a.project}</strong>{a.project==='virtual'&&<small className="ticker">VIRTUAL</small>}</TableCell><TableCell><span className="kind">{a.kind}</span></TableCell><TableCell className="numeric">{editable&&['bybit','aster'].includes(a.mode)?'账户权益':a.quantity===null?'—':money(a.quantity,a.quantity%1?4:0)}</TableCell><TableCell className="numeric">{editable&&['bybit','aster'].includes(a.mode)?'—':a.price===null?'—':money(a.price,a.price<1?6:2)}</TableCell><TableCell className="numeric asset-value">{a.value===null?'—':money(a.value)}</TableCell>{editable&&<><TableCell><span title={a.error} className={'status '+(a.mode==='manual'?'':a.error||badge(a,now).includes('旧值')||badge(a,now).includes('待')?'amber':'live')}>{badge(a,now)}</span><small className="ticker">{stamp(a.updatedAt)}</small></TableCell><TableCell>{['bybit','aster'].includes(a.mode)?<button className="icon-button" aria-label={'查看 '+a.project+' 资产'} onClick={()=>a.details?setDetail(a):connection(a.mode as 'bybit'|'aster')}><Eye size={16}/></button>:<button className="icon-button" aria-label={'编辑 '+a.project+' '+a.kind} onClick={()=>edit(a)}><Pencil size={15}/></button>}</TableCell></>}</TableRow>)}</TableBody></Table>;
 return <SidebarProvider style={{'--sidebar-width':'14rem'} as React.CSSProperties}><Sidebar className="ledger-sidebar"><SidebarHeader><div className="brand"><Wallet/><div>资产统计<small>个人资产账本</small></div></div></SidebarHeader><SidebarContent><SidebarMenu>{nav.map(({id,label,Icon})=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>navigate(id)}><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="privacy"><ShieldCheck size={18}/><span>独立密码保护</span><button className="button" onClick={async()=>{try{const response=await fetch('/api/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!response.ok)throw new Error();window.location.assign('/login');}catch{toast.error('退出失败，请重试');}}}>退出</button></div></SidebarFooter></Sidebar>
 <main className="workspace"><header className="topbar"><div><SidebarTrigger/> 我的账本 / {viewNames[view]}</div><span>{new Date(now).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'long',day:'numeric'})}</span></header><div className="page"><div className="page-heading"><div><h1>{viewNames[view]}</h1><p>{view==='overview'?'实时估值与手动资产，统一记录。':view==='history'?'保留原表记录；每天保存最近一次更新。':view==='withdrawals'?'登记出金，观察剔除提款影响后的资产变化。':'只读获取账户资产，密钥仅加密保存在服务端。'}</p></div><button className="button primary" disabled={busy} onClick={()=>void refresh(true)}><RefreshCw className={busy?'loading-spin':''} size={16}/>{busy?'正在更新':'刷新资产'}</button></div>
 {ledger.dataKind==='example'&&<div className="notice import-notice"><div><strong>当前为示例数据，尚未导入你的原表</strong><p>这里的资产和金额是演示内容。导入原表后才会显示你的真实持仓和历史。</p></div><button className="button primary" disabled={busy} onClick={()=>toggleImport(true)}>导入原表数据</button></div>}
 {error&&<div className="notice" role="alert">{error}。当前显示上次已保存的数据。</div>}
 {view==='overview'&&<><section className="summary"><div><div className="metric-label">表内总额 <span>USD · 原口径</span></div><div className="total-number">$ {money(total)}</div><p className="muted">折合人民币 ¥ {money(total*ledger.fx)} <button className="text-button" aria-label="编辑人民币汇率" onClick={()=>{setFx(String(ledger.fx));setFormError('');setFxOpen(true);}}><Pencil size={12}/></button></p></div><div className="secondary-metric"><div className="metric-label">交易所资产</div><strong>$ {money(ledger.assets.filter(a=>a.mode==='bybit'||a.mode==='aster').reduce((s,a)=>s+(a.value??0),0))}</strong><span className={'status '+(pending?'amber':'live')}>{pending?pending+' 个账户待连接':'只读账户已连接'}</span></div><div className="secondary-metric"><div className="metric-label">积分预估价值</div><strong>$ {money(ledger.assets.filter(a=>a.kind.includes('积分')).reduce((s,a)=>s+(a.value??0),0))}</strong><span className="muted">沿用表格估值，可手动编辑</span></div></section>
 {failures.length>0&&<div className="notice" role="status">{failures.map(a=>a.project+'：'+a.error).join('；')}</div>}
 <section className="withdrawal-summary" aria-label="出金调整口径"><div><span>实际持有资产 / USD</span><strong>$ {money(measures.held)}</strong><p>表内总额减去原表“出金”</p></div><div className="adjusted-metric"><span>剔除出金影响 / USD</span><strong>$ {money(measures.adjusted)}</strong><p>实际持有资产 + 累计出金</p></div><div><span>累计出金 / USD</span><strong>$ {money(measures.withdrawn)}</strong><button className="text-button" onClick={()=>navigate('withdrawals')}>管理出金记录 <ArrowUpRight size={14}/></button></div></section>
 <div className="chart-grid"><AssetTrend ledger={ledger} today={today} onHistory={()=>navigate('history')}/>
 <section className="panel sync-panel"><div className="panel-title"><h2>数据连接</h2><ShieldCheck size={18}/></div>{(['bybit','aster'] as const).map(name=><button className="connection-row" key={name} onClick={()=>connection(name)}><div className={'exchange-mark '+name}>{name==='bybit'?'B':'A'}</div><div><strong>{name==='bybit'?'Bybit':'Aster'}</strong><small>{ledger.connections[name].configured?'已连接 · '+stamp(ledger.connections[name].lastSync):'待连接只读接口'}</small></div><ChevronRight size={17}/></button>)}<div className="connection-row"><div className="exchange-mark virtual">V</div><div><strong>Virtual</strong><small>实时单价 · 数量手动</small></div></div><div className="sync-note">页面打开时每 60 秒刷新<br/>1 USD = {ledger.fx} CNY（手动汇率）</div></section></div>
 <section className="panel holdings"><div className="holdings-heading"><h2>资产明细 <span>{rows.length}</span></h2><Tabs value={filter} onValueChange={setFilter}><TabsList><TabsTrigger value="all">全部资产</TabsTrigger><TabsTrigger value="auto">自动更新</TabsTrigger><TabsTrigger value="manual">手动维护</TabsTrigger></TabsList></Tabs></div>{renderTable(rows)}</section></>}
 {view==='history'&&<><div className="notice">原表未来预填和导入前示例不计入曲线。同日多份记录在此保留；曲线优先采用日快照，其次采用最后一份原表记录。出金调整只影响派生口径，表内总额保持原值。</div><section className="panel holdings"><Table><TableHeader><TableRow><TableHead>日期（北京时间）</TableHead><TableHead>来源</TableHead><TableHead className="numeric">表内总额 / USD</TableHead><TableHead className="numeric">实际持有 / USD</TableHead><TableHead className="numeric">累计出金 / USD</TableHead><TableHead className="numeric">剔除出金影响 / USD</TableHead><TableHead className="numeric">汇率</TableHead><TableHead className="numeric">原总额 / CNY</TableHead><TableHead>核对 / 明细</TableHead></TableRow></TableHeader><TableBody>{[...ledger.history].sort((a,b)=>b.date.localeCompare(a.date)).map(p=>{const values=periodMeasures(p,ledger),included=!p.future&&!p.archived;return <TableRow key={p.id}><TableCell>{p.date}</TableCell><TableCell><span className={'status '+(p.future||p.partial?'amber':'')}>{p.archived?'导入前示例记录':p.future?'原表预填':p.id.startsWith('daily-')?(p.partial?'当日快照 · 含旧值':'当日最后更新'):'原表 '+p.id}</span></TableCell><TableCell className="numeric">{money(p.total)}</TableCell><TableCell className="numeric">{included?money(values.held):'—'}</TableCell><TableCell className="numeric">{included?money(values.withdrawn):'—'}</TableCell><TableCell className="numeric">{included?money(values.adjusted):'—'}</TableCell><TableCell className="numeric">{p.fx}</TableCell><TableCell className="numeric">{money(p.cny)}</TableCell><TableCell><button className="text-button" onClick={()=>void openPeriod(p)}>{p.difference?'合计差异 $ '+money(p.difference):'查看明细'}</button></TableCell></TableRow>;})}</TableBody></Table></section><p className="help section-note">日快照在刷新或编辑时保存；页面关闭期间不补造记录。入金未剔除，资产变化不等于投资收益。</p></>}
 {view==='withdrawals'&&<WithdrawalsPanel ledger={ledger} today={today} busy={busy} error={formError} mutate={mutate} clearError={()=>setFormError('')}/>}
 {view==='connections'&&<div className="connections-grid">{(['bybit','aster'] as const).map(name=><section className="panel connection-card" key={name}><div className="connection-card-title"><div className={'exchange-mark '+name}>{name==='bybit'?'B':'A'}</div><h2>{name==='bybit'?'Bybit':'Aster'}</h2><span className={'status '+(ledger.connections[name].configured?'live':'amber')}>{ledger.connections[name].configured?'已连接':'未连接'}</span></div><p className="help">{name==='bybit'?'统一账户净权益与资金账户余额；包含未实现盈亏，不重复累加保证金。':'使用 API Pro 钱包地址和私钥读取合约净权益，可同时读取现货余额。范围不含质押资产。'}</p><p className="help section-note">最近成功同步：{stamp(ledger.connections[name].lastSync)}</p>{ledger.connections[name].error&&<p className="error-text">{ledger.connections[name].error}</p>}<div className="form-actions"><button className="button primary" onClick={()=>connection(name)}>{ledger.connections[name].configured?'更新连接':'连接账户'}</button></div></section>)}</div>}
 <footer className="page-footer">{ledger.dataKind==='example'?'示例账本 · 尚未导入原表':'源自《资产统计.xlsx》'} · 起始持仓 {ledger.baselineDate} · 自 {ledger.startedAt} 开始更新</footer></div></main>
 <Dialog open={!!editing} onOpenChange={v=>!v&&setEditing(null)}><DialogContent><DialogHeader><DialogTitle>编辑 {editing?.project}</DialogTitle><DialogDescription>{editing?.kind} · {editing?.mode==='market'?'单价按行情更新，持仓数量手动维护。':'修改后重新计算估值，并保存当日快照。'}</DialogDescription></DialogHeader><form className="form-grid" onSubmit={e=>{e.preventDefault();if(editing)void mutate('/api/ledger','PATCH',{id:editing.id,quantity:Number(quantity),price:price===''?null:Number(price)},()=>setEditing(null));}}><label>数量<input type="number" min="0" step="any" required value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>单价 / USD<input type="number" min="0" step="any" value={price} disabled={editing?.mode==='market'} onChange={e=>setPrice(e.target.value)}/></label><p className="help">估值：{price===''?'待填写单价':'$ '+money(Number(quantity)*Number(price))}</p>{formError&&<p className="error-text" role="alert">{formError}</p>}<div className="form-actions"><button type="button" className="button" onClick={()=>setEditing(null)}>取消</button><button className="button primary" disabled={busy}>保存修改</button></div></form></DialogContent></Dialog>
 <Dialog open={fxOpen} onOpenChange={setFxOpen}><DialogContent><DialogHeader><DialogTitle>人民币换算汇率</DialogTitle><DialogDescription>沿用原表的手动汇率；修改不影响过去快照。</DialogDescription></DialogHeader><form className="form-grid" onSubmit={e=>{e.preventDefault();void mutate('/api/ledger','PATCH',{fx:Number(fx)},()=>setFxOpen(false));}}><label>1 USD 折合 CNY<input type="number" min="0.001" step="any" required value={fx} onChange={e=>setFx(e.target.value)}/></label>{formError&&<p className="error-text" role="alert">{formError}</p>}<button className="button primary" disabled={busy}>保存汇率</button></form></DialogContent></Dialog>
 <Dialog open={!!connectTo} onOpenChange={v=>{if(!v){setConnectTo(null);setSecret('');setKey('');}}}><DialogContent><DialogHeader><DialogTitle>连接 {connectTo==='bybit'?'Bybit':'Aster'}</DialogTitle><DialogDescription>{connectTo==='bybit'?'验证只读权限与余额，成功后加密保存。':'使用 API Pro 钱包地址及对应私钥，校验匹配并读取余额后加密保存。'}</DialogDescription></DialogHeader><form className="form-grid" onSubmit={e=>{e.preventDefault();void mutate('/api/connections','POST',connectTo==='bybit'?{exchange:'bybit',apiKey:key.trim(),apiSecret:secret.trim(),region}:{exchange:'aster',walletAddress:key.trim(),privateKey:secret.trim(),includeSpot},()=>{setConnectTo(null);setKey('');setSecret('');});}}><label>{connectTo==='bybit'?'API Key':'API 钱包地址'}<input autoComplete="off" spellCheck={false} autoCapitalize="none" placeholder={connectTo==='aster'?'0x…':undefined} required value={key} onChange={e=>setKey(e.target.value)}/></label><label>{connectTo==='bybit'?'API Secret':'API 钱包私钥'}<input type="password" autoComplete="new-password" spellCheck={false} autoCapitalize="none" required value={secret} onChange={e=>setSecret(e.target.value)}/></label>{connectTo==='bybit'?<><label>账户地区<Select value={region} onValueChange={setRegion}><SelectTrigger aria-label="账户地区"><SelectValue/></SelectTrigger><SelectContent>{[['global','国际站'],['nl','荷兰'],['tr','土耳其'],['kz','哈萨克斯坦'],['ge','格鲁吉亚'],['ae','阿联酋'],['eu','欧洲']].map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label><p className="help">HMAC 类型只读 API，需要账户与资产读取权限；不读取子账户及理财产品。</p></>:<><label className="checkbox-label"><Checkbox checked={includeSpot} onCheckedChange={v=>setIncludeSpot(v===true)}/>同时同步现货账户</label><p className="help">填写 Aster「API Pro」页面生成的 API 钱包地址和私钥；不需要主钱包私钥。私钥仅在服务端签名并加密保存，程序仅查询余额。</p></>}{formError&&<p className="error-text" role="alert">{formError}</p>}<div className="form-actions">{connectTo&&ledger.connections[connectTo].configured&&<button type="button" className="button" disabled={busy} onClick={()=>void mutate('/api/connections','DELETE',{exchange:connectTo},()=>{setConnectTo(null);setKey('');setSecret('');})}>断开并保留估值</button>}<button className="button primary" disabled={busy}>{busy?'验证中…':'验证并连接'}</button></div></form></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="detail-dialog"><DialogHeader><DialogTitle>{detail?.project} 账户明细</DialogTitle><DialogDescription>最近同步 {stamp(detail?.updatedAt??null)} · 美元净权益</DialogDescription></DialogHeader><div className="holdings"><Table><TableHeader><TableRow><TableHead>账户 / 币种</TableHead><TableHead className="numeric">数量</TableHead><TableHead className="numeric">美元价值</TableHead></TableRow></TableHeader><TableBody>{detail?.details?.map((b,i)=><TableRow key={i}><TableCell>{b.account}<small className="ticker">{b.coin}</small></TableCell><TableCell className="numeric">{money(b.quantity,6)}</TableCell><TableCell className="numeric">{money(b.value)}</TableCell></TableRow>)}</TableBody></Table></div><p className="help">账户合计采用交易所净权益。币种行仅供核对，不将保证金和持仓名义价值再次计入。</p></DialogContent></Dialog>
 <Dialog open={!!period} onOpenChange={v=>!v&&setPeriod(null)}><DialogContent className="detail-dialog"><DialogHeader><DialogTitle>{period?.date} 资产快照</DialogTitle><DialogDescription>{period?.archived?'导入前示例记录':period?.future?'原表预填记录':period?.id.startsWith('daily-')?'当日最近一次已保存数据':'原表 '+period?.id} · 总额 $ {money(period?.total??0)}</DialogDescription></DialogHeader>{period?.difference!==0&&<p className="notice">行估值之和与原合计相差 $ {money(period?.difference??0)}。保留原合计，未修改历史。</p>}{formError?<p className="error-text">{formError}</p>:periodRows.length?<div className="holdings">{renderTable(periodRows,false)}</div>:<p className="help">读取快照…</p>}</DialogContent></Dialog>
 <ImportLedgerDialog open={importOpen} onOpenChange={toggleImport} onImported={data=>{setLedger(data);setError('');setNow(Date.now());}}/>
 <Toaster position="bottom-right" richColors/></SidebarProvider>;
}
